version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/test-project/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/fake-engine-package/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
  
  
